/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/Medea.gltf -o src/Medea.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations  } from '@react-three/drei'

export function Medea(props) {

  

  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Medea.gltf');
  const { actions } = useAnimations(animations, group);
  console.log(actions)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mdea_mesh_1.geometry} material={materials.Mdea_MAT} />
      <mesh geometry={nodes.Mdea_mesh_2.geometry} material={materials.Mdea_MAT_} />
    </group>
  )
}

useGLTF.preload('/models/Medea.gltf')
